"""modules/groq_client.py — Groq API wrapper and prompt templates."""
from __future__ import annotations
import json


def build_profile_summary(profile: dict, health_score: dict) -> dict:
    """Build a compact profile summary dict to send to Groq."""
    columns_profile = profile.get("columns", {})
    quality = profile.get("quality", {})
    outlier_data = profile.get("outliers", {})
    corr_data = profile.get("correlations", {})
    ml = profile.get("ml_readiness", {})

    dtype_counts = {}
    for v in columns_profile.values():
        cls = v.get("dtype_class", "unknown")
        dtype_counts[cls] = dtype_counts.get(cls, 0) + 1

    top_missing = sorted(
        [(col, v["pct"]) for col, v in quality.get("missing_values", {}).items()],
        key=lambda x: x[1], reverse=True,
    )[:5]

    top_outliers = sorted(
        [(col, v["outlier_pct"]) for col, v in outlier_data.items()],
        key=lambda x: x[1], reverse=True,
    )[:5]

    return {
        "dataset_info": {
            "rows": profile.get("meta", {}).get("rows", 0),
            "columns": profile.get("meta", {}).get("columns", 0),
            "memory_mb": round(profile.get("meta", {}).get("memory_mb", 0), 2),
            "column_types": dtype_counts,
        },
        "top_missing_columns": top_missing,
        "top_outlier_columns": top_outliers,
        "high_correlation_pairs": corr_data.get("high_correlation_pairs", [])[:5],
        "duplicate_rows_pct": quality.get("duplicate_rows", {}).get("pct", 0),
        "ml_problem_type": ml.get("problem_type", "unknown"),
        "ml_ready": ml.get("is_ready", False),
        "blockers": ml.get("blockers", []),
        "warnings_count": len(ml.get("warnings", [])),
        "recommended_models": [m["name"] for m in ml.get("recommended_models", [])[:3]],
        "preprocessing_steps": {
            col: v.get("imputation", "?")
            for col, v in profile.get("preprocessing_recommendations", {}).items()
            if not v.get("drop", False)
        },
        "feature_engineering_count": len(profile.get("feature_engineering", [])),
        "health_score": health_score.get("total", 0),
        "health_grade": health_score.get("grade", "?"),
        "worst_dimension": health_score.get("worst_dimension", ""),
    }


def get_ai_explanation(profile_summary: dict, groq_api_key: str) -> str:
    """Call Groq API and return AI-generated analysis narrative with fallback support."""
    try:
        from groq import Groq
    except ImportError:
        return "⚠️ Groq package not installed. Run: pip install groq"

    if not groq_api_key or groq_api_key.strip() == "":
        return "⚠️ No Groq API key provided. Enter your key in the sidebar to enable AI explanations."

    client = Groq(api_key=groq_api_key.strip())

    system_prompt = """You are a senior data scientist writing a professional analysis report.

RULES:
- Write in structured sections using markdown headers (##)
- Be specific — use the actual numbers from the data, not generic statements
- Never write "the data shows" or "it can be seen that" — these are filler phrases
- Use precise statistical language: skewness, kurtosis, cardinality, multicollinearity
- Every recommendation must be actionable, not vague
- Write as if this report will be read by a hiring manager or technical evaluator
- Each section should be 3–6 sentences

OUTPUT FORMAT (use exactly these 8 headers):
## Dataset Overview
## Key Statistical Findings
## Data Quality Issues
## Recommended Cleaning Steps
## Machine Learning Strategy
## Risk Factors
## Feature Engineering Opportunities
## Final Recommendation"""

    user_prompt = f"""Analyse this dataset summary and write a structured data science report:

{json.dumps(profile_summary, indent=2, default=str)}

Be specific about the numbers. Reference the actual column counts, percentages, and model names from the summary above."""

    models = [
        "llama-3.3-70b-versatile",
        "llama-3.1-8b-instant",
        "qwen/qwen3-32b",
        "groq/compound",
    ]

    last_error = None
    for model in models:
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.3,
                max_tokens=2000,
            )
            report = response.choices[0].message.content
            return f"> *Generated by {model}*\n\n{report}"
        except Exception as e:
            last_error = e
            continue

    return f"⚠️ Groq API error (tried all fallback models): {str(last_error)}\n\nPlease verify your API key or network connection."


def chat_with_dataset(
    messages: list[dict],
    profile_summary: dict,
    groq_api_key: str,
    model_context: dict | None = None,
) -> str:
    """Multi-turn chat grounded in the dataset profile + (optional) chosen model.

    `messages` is the running conversation as a list of {"role": "user"|"assistant", "content": str}.
    Returns the assistant's next reply (markdown), using the same Q&A fallback chain.
    """
    try:
        from groq import Groq
    except ImportError:
        return "⚠️ Groq package not installed. Run: pip install groq"

    if not groq_api_key or groq_api_key.strip() == "":
        return "⚠️ No Groq API key provided. Enter your key in the sidebar to enable the AI chat."

    client = Groq(api_key=groq_api_key.strip())

    context = json.dumps(profile_summary, indent=2, default=str)[:3000]
    model_line = ""
    if model_context:
        model_line = (
            f"\nThe user is currently working on a "
            f"{model_context.get('problem_type', 'unknown')} problem"
            + (f", target column '{model_context['target']}'" if model_context.get("target") else "")
            + (f", model '{model_context['model_name']}'" if model_context.get("model_name") else "")
            + "."
        )

    system_prompt = (
        "You are a senior data scientist embedded in the DataIQ app, helping the user build an ML "
        "model on THEIR dataset. Be concrete and reference the dataset's actual numbers from the "
        "context below. Keep answers focused (2–6 sentences or a short list). Suggest specific models, "
        "preprocessing, metrics, and hyperparameters. When useful, give a short Python/sklearn snippet."
        f"{model_line}\n\nDATASET PROFILE (JSON):\n{context}"
    )

    # Keep only the recent turns to bound the context.
    history = [
        {"role": m["role"], "content": str(m["content"])}
        for m in messages
        if m.get("role") in ("user", "assistant") and m.get("content")
    ][-12:]

    api_messages = [{"role": "system", "content": system_prompt}] + history

    models = [
        "llama-3.1-8b-instant",
        "groq/compound-mini",
        "llama-3.3-70b-versatile",
    ]
    last_error = None
    for model in models:
        try:
            response = client.chat.completions.create(
                model=model,
                messages=api_messages,
                temperature=0.4,
                max_tokens=700,
            )
            return response.choices[0].message.content
        except Exception as e:
            last_error = e
            continue
    return f"⚠️ Groq API error (tried all fallback models): {last_error}"


def get_quick_insight(question: str, profile_summary: dict, groq_api_key: str) -> str:
    """Get a quick one-paragraph insight for a specific question with fallback support."""
    try:
        from groq import Groq
        if not groq_api_key:
            return "No API key provided."
        client = Groq(api_key=groq_api_key.strip())
        context = json.dumps(profile_summary, indent=2, default=str)[:3000]

        models = [
            "llama-3.1-8b-instant",
            "groq/compound-mini",
            "llama-3.3-70b-versatile",
        ]

        last_error = None
        for model in models:
            try:
                response = client.chat.completions.create(
                    model=model,
                    messages=[
                        {"role": "system", "content": "You are a data scientist. Answer concisely in 2-4 sentences."},
                        {"role": "user", "content": f"Dataset context:\n{context}\n\nQuestion: {question}"},
                    ],
                    temperature=0.3,
                    max_tokens=300,
                )
                answer = response.choices[0].message.content
                return f"> *Answered by {model}*\n\n{answer}"
            except Exception as e:
                last_error = e
                continue
        return f"Error (tried all models): {last_error}"
    except Exception as e:
        return f"Error: {e}"
