"""modules/reporter.py — HTML, JSON, Markdown report generation."""
from __future__ import annotations
import json
import io
from datetime import datetime
import pandas as pd


def _safe_json(obj):
    """JSON serialiser for non-standard types."""
    if isinstance(obj, (pd.Timestamp,)):
        return str(obj)
    if hasattr(obj, "item"):
        return obj.item()
    return str(obj)


def generate_json_report(profile: dict) -> str:
    """Serialize the full profile dict to formatted JSON."""
    return json.dumps(profile, indent=2, default=_safe_json)


def generate_markdown_report(profile: dict, health_score: dict, groq_report: str = "") -> str:
    """Generate a concise Markdown report suitable for GitHub README."""
    meta = profile.get("meta", {})
    quality = profile.get("quality", {})
    ml = profile.get("ml_readiness", {})
    columns_profile = profile.get("columns", {})

    lines = [
        f"# DataIQ Report — {meta.get('file_name', 'Unknown')}",
        f"*Generated on {datetime.now().strftime('%Y-%m-%d %H:%M')} by DataIQ*",
        "",
        "---",
        "",
        "## Dataset Overview",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Rows | {meta.get('rows', 'N/A'):,} |",
        f"| Columns | {meta.get('columns', 'N/A')} |",
        f"| Memory | {meta.get('memory_mb', 0):.2f} MB |",
        f"| Health Score | **{health_score.get('total', 0):.1f}/100** (Grade {health_score.get('grade', '?')}) |",
        f"| ML Problem Type | {ml.get('problem_type', 'unknown').title()} |",
        "",
        "## Column Types",
        "",
    ]

    # Dtype counts
    from collections import Counter
    dtype_counts = Counter(v.get("dtype_class") for v in columns_profile.values())
    lines += ["| Type | Count |", "|------|-------|"]
    for dtype, cnt in sorted(dtype_counts.items()):
        lines.append(f"| {dtype.title()} | {cnt} |")
    lines.append("")

    # Health Score Breakdown
    lines += [
        "## Health Score Breakdown",
        "",
        "| Dimension | Score |",
        "|-----------|-------|",
        f"| Missing Values | {health_score.get('missing_score', 0):.1f} |",
        f"| Outliers | {health_score.get('outlier_score', 0):.1f} |",
        f"| Duplicates | {health_score.get('duplicate_score', 0):.1f} |",
        f"| Class Balance | {health_score.get('class_balance_score', 0):.1f} |",
        f"| Correlations | {health_score.get('correlation_score', 0):.1f} |",
        "",
        f"> **Priority fix:** {health_score.get('one_line_fix', '')}",
        "",
    ]

    # Data Quality
    missing = quality.get("missing_values", {})
    dup_count = quality.get("duplicate_rows", {}).get("count", 0)
    lines += [
        "## Data Quality",
        "",
        f"- **Duplicate rows:** {dup_count:,}",
        f"- **Columns with missing values:** {len(missing)}",
        "",
    ]
    if missing:
        lines += ["| Column | Missing % | Severity |", "|--------|-----------|----------|"]
        for col, v in sorted(missing.items(), key=lambda x: x[1]["pct"], reverse=True)[:10]:
            lines.append(f"| {col} | {v['pct']*100:.1f}% | {v['severity']} |")
        lines.append("")

    # ML Readiness
    lines += [
        "## ML Readiness",
        "",
        f"- **Detected problem type:** {ml.get('problem_type', '?').title()} "
        f"(confidence: {ml.get('problem_confidence', 0)*100:.0f}%)",
        f"- **Target column:** {ml.get('target_column', 'Not detected')}",
        f"- **Ready for ML:** {'Yes' if ml.get('is_ready') else 'No — address blockers first'}",
        "",
    ]
    blockers = ml.get("blockers", [])
    if blockers:
        lines += ["**Blockers:**"]
        for b in blockers:
            lines.append(f"- {b}")
        lines.append("")

    rec_models = [m["name"] for m in ml.get("recommended_models", [])[:3]]
    if rec_models:
        lines += [f"**Recommended models:** {', '.join(rec_models)}", ""]

    # AI Report
    if groq_report:
        lines += ["---", "", "## AI Analysis (Groq LLM)", "", groq_report, ""]

    lines += ["---", "", "*Report generated by [DataIQ](https://github.com)*"]
    return "\n".join(lines)


def generate_html_report(
    profile: dict,
    health_score: dict,
    groq_report: str = "",
    charts_b64: dict = None,
) -> str:
    """Generate a self-contained HTML report using Jinja2."""
    try:
        from jinja2 import Template
    except ImportError:
        return "<html><body><h1>jinja2 not installed</h1></body></html>"

    TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DataIQ Report — {{ meta.file_name }}</title>
<style>
  body { font-family: 'Inter', sans-serif; background: #0f0f1a; color: #e2e8f0; margin: 0; padding: 2rem; }
  h1 { color: #8b5cf6; }
  h2 { color: #c4b5fd; border-bottom: 1px solid #374151; padding-bottom: 0.5rem; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { padding: 0.5rem 1rem; border: 1px solid #374151; text-align: left; }
  th { background: #1e1b4b; color: #a78bfa; }
  .card { background: #1a1a2e; border: 1px solid #374151; border-radius: 12px; padding: 1.5rem; margin: 1rem 0; }
  .badge-A { color: #10b981; } .badge-B { color: #3b82f6; }
  .badge-C { color: #f59e0b; } .badge-D { color: #ef4444; }
  .score { font-size: 2rem; font-weight: 800; }
  pre { background: #111827; padding: 1rem; border-radius: 8px; overflow-x: auto; }
</style>
</head>
<body>
<h1>📊 DataIQ Report — {{ meta.file_name }}</h1>
<p><em>Generated {{ timestamp }}</em></p>

<div class="card">
  <h2>Dataset Overview</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Rows</td><td>{{ "{:,}".format(meta.rows) }}</td></tr>
    <tr><td>Columns</td><td>{{ meta.columns }}</td></tr>
    <tr><td>Memory</td><td>{{ "%.2f"|format(meta.memory_mb) }} MB</td></tr>
    <tr><td>Health Score</td><td class="score badge-{{ health.grade }}">{{ health.total }}/100 — Grade {{ health.grade }}</td></tr>
    <tr><td>ML Problem Type</td><td>{{ ml_type | title }}</td></tr>
  </table>
</div>

<div class="card">
  <h2>Health Score Breakdown</h2>
  <table>
    <tr><th>Dimension</th><th>Score</th></tr>
    <tr><td>Missing Values</td><td>{{ health.missing_score }}</td></tr>
    <tr><td>Outliers</td><td>{{ health.outlier_score }}</td></tr>
    <tr><td>Duplicates</td><td>{{ health.duplicate_score }}</td></tr>
    <tr><td>Class Balance</td><td>{{ health.class_balance_score }}</td></tr>
    <tr><td>Correlations</td><td>{{ health.correlation_score }}</td></tr>
  </table>
  <p><strong>Priority fix:</strong> {{ health.one_line_fix }}</p>
</div>

{% if missing %}
<div class="card">
  <h2>Missing Values</h2>
  <table>
    <tr><th>Column</th><th>Missing %</th><th>Severity</th></tr>
    {% for col, v in missing.items() %}
    <tr><td>{{ col }}</td><td>{{ "%.1f"|format(v.pct * 100) }}%</td><td>{{ v.severity }}</td></tr>
    {% endfor %}
  </table>
</div>
{% endif %}

{% if groq_report %}
<div class="card">
  <h2>🧠 AI Analysis</h2>
  <div>{{ groq_report | replace('\\n', '<br>') }}</div>
</div>
{% endif %}

</body>
</html>"""

    meta = profile.get("meta", {})
    quality = profile.get("quality", {})
    ml = profile.get("ml_readiness", {})

    t = Template(TEMPLATE)
    return t.render(
        meta=type("M", (), meta)(),
        health=type("H", (), health_score)(),
        ml_type=ml.get("problem_type", "unknown"),
        missing=quality.get("missing_values", {}),
        groq_report=groq_report,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
    )
